---
apiVersion: v1
kind: Pod
metadata:
  name: config-volume
  labels:
    app: nginx
spec:
  containers:
    - name: sample-app
      image: nginx:alpine
      volumeMounts:
      - name: config-volume
        mountPath: /usr/share/nginx/html
  volumes:
    - name: config-volume
      configMap:
        name: user-config
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-svc
            port:
              number: 80
